---
engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  duplication:
    enabled: false
  brakeman:
    enabled: true
  reek:
    enabled: true
  "bundler-audit":
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - lib/**
  - "**.rb"
  - "**.md"
exclude_paths:
- .travis/**/*
- test/**/*