language: ruby
sudo: false
cache: bundler
before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq sqlite3
#addons:
#  mariadb: '10.0'
services:
  - mysql
  - postgresql
before_script:
  - mysql -e 'create database arext_test;'
  - psql -c 'create database arext_test;' -U postgres
script:
  - "bundle exec rake test"
#  - "bundle exec rake test:sqlite3"
  - "gem build arel-extensions.gemspec"
#  - "ruby test/real_db_test.rb"
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
rvm:
  - rbx-2
  - jruby-9.0.5.0
  - jruby-head
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - ruby-head
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - openjdk6
matrix:
  fast_finish: true
#  allow_failures:
#    - rvm: jruby-9.0.5.0
#    - rvm: jruby-head
#    - rvm: ruby-head
#    - rvm: jruby-head
bundler_args: --jobs 3 --retry 3
notifications:
  email: false