language: ruby
sudo: false
cache: bundler
before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq sqlite3
#addons:
#  mariadb: '10.0'
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
services:
  - mysql
  - postgresql
before_script:
  - mysql -e 'create database arext_test;'
  - psql -c 'create database arext_test;' -U postgres
script:
  - "bundle exec rake test"
#  - "bundle exec rake test:sqlite3"
  - "gem build arel_extensions.gemspec"
#  - "ruby test/real_db_test.rb"
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
rvm:
  - rbx-2
  - jruby-9.0.5.0
  - jruby-head
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - ruby-head
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
#  - openjdk6
matrix:
  fast_finish: true
  exclude:
    - rvm: rbx-2
      jdk: openjdk7
    - rvm: rbx-2
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.1
      jdk: openjdk7
    - rvm: 2.1
      jdk: oraclejdk7
    - rvm: 2.2.5
      jdk: openjdk7
    - rvm: 2.2.5
      jdk: oraclejdk7
    - rvm: 2.3.1
      jdk: openjdk7
    - rvm: 2.3.1
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
  allow_failures:
#    - rvm: jruby-9.0.5.0
#    - rvm: jruby-head
    - rvm: ruby-head
      gemfile: gemfiles/rails4.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails3.gemfile
#    - rvm: jruby-head
bundler_args: --jobs 2 --retry 2
notifications:
  email: false