version: "{build}"

cache:
  - vendor/bundle

branches:
  only:
    - master

services:
  - mssql2014


install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

# Disable normal Windows builds in favor of our test script.
build: off


before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - ps: Start-Service 'MSSQL$SQL2014'

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bundle exec rake test
  - bundle exec rake test:mssql

environment:
  matrix:
    - RUBY_VERSION: 193
    - RUBY_VERSION: 200
    - RUBY_VERSION: 21
    - RUBY_VERSION: 22
    - RUBY_VERSION: 23
